# Generated by Django 5.2.5 on 2025-09-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('customer', 'Customer')], default='customer', max_length=10),
        ),
    ]
